steps:
  - read: npm_scope
    prompt: What scope should this extension be listed under on NPM (e.g. @patternfly, @yourorg, etc.)?

  - read: extension_name
    prompt: What is the name of your extension?

  - read: extension_description
    prompt: What will your extension do?

  - read: repo_url
    prompt: What is the URL of your repo remote?

  - copy: .recipes/default/README.md
    to: 'README.md'
  - update: README.md
  
  - copy: .recipes/default/package.json
    to: 'package.json'
  - update: package.json

  - copy: .recipes/default/packages/module/package.json
    to: 'packages/module/package.json'
  - update: packages/module/package.json

  - copy: .recipes/default/packages/module/patternfly-docs/content/extensions/patternfly-extension-seed/examples/basic.md
    to: 'packages/module/patternfly-docs/content/extensions/{{ extension_name | kebab-case }}/examples/basic.md'

  - copy: .recipes/default/packages/module/patternfly-docs/content/extensions/patternfly-extension-seed/examples/Basic.tsx
    to: 'packages/module/patternfly-docs/content/extensions/{{ extension_name | kebab-case }}/examples/Basic.tsx'

  - copy: .recipes/default/packages/module/patternfly-docs/content/extensions/patternfly-extension-seed/design-guidelines/design-guidelines.md
    to: 'packages/module/patternfly-docs/content/extensions/{{ extension_name | kebab-case }}/design-guidelines/design-guidelines.md'

  - copy: .recipes/default/packages/module/patternfly-docs/generated/index.js
    to: packages/module/patternfly-docs/generated/index.js
  - update: packages/module/patternfly-docs/generated/index.js

  - copy: .recipes/default/packages/module/patternfly-docs/generated/extensions/patternfly-extension-seed/design-guidelines.js
    to: 'packages/module/patternfly-docs/generated/extensions/{{ extension_name | kebab-case }}/design-guidelines.js'

  - copy: .recipes/default/packages/module/patternfly-docs/generated/extensions/patternfly-extension-seed/react.js
    to: 'packages/module/patternfly-docs/generated/extensions/{{ extension_name | kebab-case }}/react.js'

  - remove: .github/workflows/add-to-project.yml
  